app:
  name: App
  port: :3000

database:
  dsn : "root:123456@tcp(127.0.0.1:3306)/go_bili?charset=utf8mb4&parseTime=True&loc=Local"
  MaxIdleConns: 10
  MaxOpenConns: 100
  Addr : "localhost:6379"
  Password : ""
  SubSwitch : "false"

JWT:
  Key : "JWT_SECRET"

RabbitMQ:
  Url: "amqp://guest:guest@localhost:5672/"

Grpc:
  Addr: "localhost:50051"