app:
  name: App
  port: :3000

database:
  # MySQL 地址直接写容器服务名 mysql
  dsn: "root:123456@tcp(mysql:3306)/go_bili?charset=utf8mb4&parseTime=True&loc=Local"
  MaxIdleConns: 10
  MaxOpenConns: 100
  # Redis 地址直接写容器服务名 redis
  Addr: "redis:6379"
  Password: ""
  SubSwitch: "false"

JWT:
  Key: "JWT_SECRET_PROD_BILI"

RabbitMQ:
  # RabbitMQ 地址直接写容器服务名 rabbitmq
  Url: "amqp://guest:guest@rabbitmq:5672/"

Grpc:
  Addr: "localhost:50051"

GitHub:
  ClientID: "Ov23li9fmt2pv1FOBoQc"
  ClientSecret: ""                                  # 故意留空，由环境变量注入
  RedirectURI: "http://43.138.153.144/api/auth/github/callback"
  FrontendURL: "http://43.138.153.144/oauth/callback"